previewsEnabled: true

envVarGroups:
  - name: EXAMPLE_ENV_VAR_GROUP
    envVars:
      - key: ENV_VAR_SYNC_FALSE
        sync: false
      - key: ELIXIR_VERSION
        value: 1.12.0

services:
  - name: render_plug
    type: web
    env: elixir
    envVars:
      - fromGroup: EXAMPLE_ENV_VAR_GROUP
    buildCommand: mix deps.get --only prod && MIX_ENV=prod mix release --overwrite
    startCommand: _build/prod/rel/render_plug/bin/render_plug start
    healthCheckPath: /
    autoDeploy: true
    plan: starter
